config/routes.rb
WdiTradr::Application.routes.draw do
  get 'users/refresh_table' => 'users#refresh_table'
  get '/stocks/graph/:symbol' => 'stocks#graph'
  get 'users/refresh_chart' => 'users#refresh_chart'
  resources :stocks, :only => [:create]

  resources :user_sessions
  resources :users

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'users#show'
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user
  attr_accessible :quantity, :starting_price, :symbol

  before_create :set_starting_price

  def set_starting_price
    # quote = StockQuote::Stock.quote(symbol)
    # self.starting_price = quote.last

    quote = Ystock.get_stock(symbol).first[1]
    self.starting_price = quote[:price]
  end

  def latest_price
    # quote = StockQuote::Stock.quote(symbol)
    # quote.last

    quote = Ystock.get_stock(symbol).first[1]
    quote[:price]
  end

  def profit
    paid_initially         = (self.starting_price * self.quantity).to_f
    latest_value_of_shares = (latest_price   * quantity).to_f

    paid_initially - latest_value_of_shares
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :email, :password, :password_confirmation, :cash

  validates_length_of :password, :minimum => 3, :message => "password must be at least 3 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password

  has_many :stocks

  def unique_stock_symbol_list
    self.stocks.select("distinct stocks.symbol").map {|s| s.symbol}.sort
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login

protected

  def not_authenticated
    redirect_to login_path, :alert => "Please login first."
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  # POST /stocks
  # POST /stocks.json
  def create
    @stock = current_user.stocks.build(params[:stock])
    @stock.save
    @stocks = current_user.stocks
    @unique_stock_symbol_list = current_user.unique_stock_symbol_list
  end

  def graph
    symbol = params[:symbol]
    render :json => {:time => Time.now, :latest_price => Stock.find_by_symbol(symbol).latest_price}

  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]

  def new
    @user = User.new
  end

  def create
    respond_to do |format|
      if @user = login(params[:email], params[:password])
        format.html { redirect_back_or_to(:user, :notice => 'Login successful.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { flash.now[:alert] = "Login failed."; render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    logout
    redirect_to(:users, :notice => 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:index, :new, :create]

  def refresh_table
    @stocks = current_user.stocks
  end

  def refresh_chart

  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
    @stocks = current_user.stocks
    @unique_stock_symbol_list = current_user.unique_stock_symbol_list

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to :users, :notice => 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = current_user
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WdiTradr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="nav">
    <% if current_user %>
      <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
      <%= link_to "Logout", :logout %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>
  </div>
  <div>
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
  </div>

  <%= yield %>

</body>
</html>

app/views/stocks/create.js.erb
$("#new_stock :input").val("");

$("#stocks").empty().html("<%= j render :partial => 'users/stocks_rows' %>");

$("#checkboxes").empty().html("<%= j render :partial => 'users/stocks_checkboxes' %>");

app/views/user_sessions/create.html.haml
%h1 UserSessions#create
%p Find me in app/views/user_sessions/create.html.haml

app/views/user_sessions/destroy.html.haml
%h1 UserSessions#destroy
%p Find me in app/views/user_sessions/destroy.html.haml

app/views/user_sessions/new.html.haml
%h1 Login

= form_tag user_sessions_path, :method => :post do
  .field
    = label_tag :email
    = text_field_tag :email
  .field
    = label_tag :password
    = password_field_tag :password
  .actions
    = submit_tag "Login"

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .field
    = f.label :cash
    = f.number_field :cash
  .actions
    = f.submit 'Save'

app/views/users/_stocks_checkboxes.html.haml
- @unique_stock_symbol_list.each do |symbol|
  = check_box_tag symbol, symbol
  = label_tag symbol

app/views/users/_stocks_rows.html.haml
%thead
  %tr
    %th Symbol
    %th Quantity
    %th Starting Price
    %th Latest Price
    %th Profit
%tbody
  - @stocks.each do |stock|
    %tr
      %td= stock.symbol
      %td= stock.quantity
      %td= stock.starting_price
      %td= stock.latest_price
      %td= number_to_currency(stock.profit)

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

This homepage used to show a table of sensitive information.

REDACTED

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/refresh_table.js.erb
$("#stocks").empty().html("<%= j render :partial => 'users/stocks_rows' %>");

app/views/users/show.html.haml
%h1= @user.email
%h2= "Cash: #{number_to_currency(@user.cash)}"

#checkboxes
  = render :partial => "stocks_checkboxes"

= form_for Stock.new, :remote => true do |f|
  = f.text_field :symbol, :placeholder => "symbol"
  = f.number_field :quantity, :placeholder => "quantity"
  = f.button "Buy", :type => "submit"

/= button_tag "Refresh", :id => "refresh_stocks"

%table#stocks
  = render :partial => "stocks_rows"

#test

%link{:rel => 'stylesheet', :href => 'http://cdn.oesmith.co.uk/morris-0.4.3.min.css'}
%script{:src  => "//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"}
%script{:src  => "//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"}
%script{:src  => "http://cdn.oesmith.co.uk/morris-0.4.3.min.js"}